name: CaosExample
options:
  bundleIdPrefix: com.andersontizaias
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "16"
  createIntermediateGroups: true

packages:
  Caos:
    path: ..

targets:
  CaosExample:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Caos
        excludes:
          - "*.playground/**"
          - CaosPlayground.playground
    resources:
      - path: Caos/Base.lproj/Main.storyboard
      - path: Caos/Base.lproj/LaunchScreen.xib
      - path: Caos/Images.xcassets
      - path: Caos/caos.yaml
    dependencies:
      - package: Caos
    settings:
      base:
        SWIFT_VERSION: "5.9"
        PRODUCT_BUNDLE_IDENTIFIER: com.andersontizaias.CaosExample
        INFOPLIST_FILE: Caos/Info.plist
